version: "3.8"

services:
  database:
    container_name: rosenkreuz-bot-db
    image: postgres:16.1
    restart: unless-stopped
    env_file: ./.env
    environment:
      - TZ=Europe/Kiev
      - POSTGRES_DB=$POSTGRES_DATABASE
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
    ports:
      - $POSTGRES_LOCAL_PORT:$POSTGRES_DOCKER_PORT

  app:
    container_name: rosenkreuz-bot-app
    depends_on:
      - database
    restart: on-failure
    build: .
    image: rosenkreuz-bot
    env_file: ./.env
    ports:
      - $SPRING_LOCAL_PORT:$SPRING_DOCKER_PORT
      - $DEBUG_PORT:$DEBUG_PORT
    environment:
      SPRING_APPLICATION_JSON: '{
             "spring.datasource.url" : "jdbc:postgresql://booking-service-db:$POSTGRES_LOCAL_PORT/$POSTGRES_DATABASE?createDatabaseIfNotExist=true",
             "spring.datasource.username" : "$POSTGRES_USER",
             "spring.datasource.password" : "$POSTGRES_PASSWORD"
           }'
      JAVA_TOOL_OPTIONS: "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005"
