name: Java CI

on:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Check out code
      - name: Check out code
        uses: actions/checkout@v2

      # Set up JDK
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
          cache: maven

      # Use preinstalled PostgreSQL
      - name: Start PostgreSQL
        run: |
            sudo systemctl start postgresql.service
            pg_isready

      # Set up test environment for PostgreSQl DB
      - name: Set up test environment
        run: |
          sudo -u postgres psql --command="CREATE USER ${POSTGRES_USERNAME} PASSWORD ${POSTGRES_PASSWORD}" --command="\du"

      # Check code style and execute tests
      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots verify
