name: Java CI

on:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Check out code
      - name: Check out code
        uses: actions/checkout@v2

      # Set up JDK
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
          cache: maven

      # Use preinstalled PostgreSQL
      - name: Start PostgreSQL
        run: |
            sudo systemctl start postgresql.service
            pg_isready

      # Set up test environment for PostgreSQl DB
      - name: Set up test environment
        run: |
          export POSTGRES_USER = test POSTGRES_PASSWORD = test POSTGRES_DATABASE = test
          sudo -u postgres psql 
          CREATE DATABASE test 
          CREATE DATABASE test WITH ENCRYPTED PASSWORD 'test'
          GRANT ALL PRIVILEGES ON DATABASE test TO test
          \du
          exit

      # Check code style and execute tests
      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots verify
